@backend_HostAddress = http://localhost:5299

### Probar el nuevo controlador ActivityController
GET {{backend_HostAddress}}/activity/
Accept: application/json

### Obtener las actividades ordenadas por tiempo
GET {{backend_HostAddress}}/activity/ordered
Accept: application/json

### Obtener las actividades ordenadas por tiempo
GET {{backend_HostAddress}}/activity/maxactivitytime
Accept: application/json

### Obtener una actividad segun su dia
GET {{backend_HostAddress}}/activity/get-achievement-by-date
Accept: application/json

### Obtener la posicion de un logro dentro de la timeline
GET {{backend_HostAddress}}/activity/calculate-timeline-position
Accept: application/json

### (Opcional) Mantener la prueba del WeatherForecast si aún lo conservas
GET {{backend_HostAddress}}/weatherforecast/
Accept: application/json
